### ISSUE TITLE
Jetson 2gb image is very large

### ISSUE THREAD

**Issue by BRFrags** [steveseguin/raspberry_ninja#14]
The image when loaded on a 32GB micro sd card won't finish as it flashes to a size over 32GB, I there a fix for this, or do I need a larger micro sd card?
Thanks, Ben

**Comment by steveseguin** [comment]
I'll need to probably re-create the image so it auto-resizes to fit the partition; I think I got this working with the Jetson images.

A 32 gb sandisk disk was used to base the image for the pi on, but not all SDs are created equal.

Good news is I'm working on this project today; currently just flashed the image fresh on my pi, so maybe I'll be able to get you something soon.

**Comment by BRFrags** [comment]
Thank you, the flashed file size came out at a few megabytes above 32 gigs so that should help

**Comment by steveseguin** [comment]
https://drive.google.com/file/d/1f1PCEpKBLT3KVZSRR6pYwywt9TKjPmwW/view?usp=sharing

Here's a new image with new code; I'd welcome testing.  I may make some more changes before re-releasing a fixed second copy.

You can configure the wifi via windows, etc.  https://github.com/steveseguin/raspberry_ninja/blob/main/raspberry_pi/README.md#setting-up-and-connecting

**Comment by steveseguin** [comment]
I've tried updating the Jetson images to be smaller, but it's not be easy so far.  Facing a lot of bootloader issues when I try to clone a backup image. 

Instead, I did update the installer for the Jetson , and it's able to complete now in about an hour or so, using the Nvidia Jetson original image.  It only has one or two prompts during the install. It won't work with a 16-gb drive really, but any 32-gb drive should work still. Ideally a fast SD card to ensure it installs quickly.

This is probably my recommendation for the being, but I haven't given up on making more compact images yet.

**Comment by thor-schueler** [comment]
You might consider going docker instead. I have been running a raspberry_ninja derivative on docker for a while now successfully on rpi3 and rpi4 and have a derivative docker image for intel based linux as well. Makes it a lot easier to manage also. The image is still large (total just under 1GB) but the layering makes it easier to manage and faster to build ....

**Comment by BRFrags** [comment]
I found out my micro SD card was a few megabytes smaller than 32GB so that's why it didn't work😁, I've since got a 64GB micro SD card and it works as intended😉.
