### ISSUE TITLE
Missing gstreamer plugins: ['sctp']

### ISSUE THREAD

**Issue by edwardchang0112** [steveseguin/raspberry_ninja#23]
On Raspberry Pi 4, I tried to run this repo with

python3 publish.py

but get the error message:

Missing gstreamer plugins: ['sctp']

then I go to /raspberry_pi/installer.sh to check if there is something I missed,
I just followed the section of "usrsctp"
'''
cd ~
git clone https://github.com/sctplab/usrsctp.git
cd usrsctp
mkdir build
sudo meson build  --prefix=/usr/local
sudo ninja -C build install -j4
sudo ldconfig
sudo libtoolize
'''

thern run python3 publish.py again
it still shows the message
Missing gstreamer plugins: ['sctp']

Any comments on this?
but it stil

**Comment by steveseguin** [comment]
Did  you use the image I provided to setup your PI?

**Comment by edwardchang0112** [comment]
> Did you use the image I provided to setup your PI?

I use the image provided by the offical website, and I already get something on my Pi...
Can I try to set up my Pi to be the same one as the image you provided?

**Comment by steveseguin** [comment]
You can use the image I provided, which has everything already installed on it. It's the RPiOS Bulleyes 32bit version, with all the files installed for Rasberry_ninja

If you try to use the official website version, you'll need to use `installer.sh`, and do a complete installation  -- you can't do just a part of it.  It will take like 1 to 4 hours to install, and it may need some system restarts if the Pi crashes at times.  

If you still get errors after installing it, you can try to fix any errors and then try re-installing it again. I won't have time to fix errors with the install script tonight, if it doesn't work -- maybe later this week tho

**Comment by edwardchang0112** [comment]
> You can use the image I provided, which has everything already installed on it. It's the RPiOS Bulleyes 32bit version, with all the files installed for Rasberry_ninja
> 
> If you try to use the official website version, you'll need to use `installer.sh`, and do a complete installation -- you can't do just a part of it. It will take like 1 to 4 hours to install, and it may need some system restarts if the Pi crashes at times.
> 
> If you still get errors after installing it, you can try to fix any errors and then try re-installing it again. I won't have time to fix errors with the install script tonight, if it doesn't work -- maybe later this week tho

I checked your demo video on YouTube, the streaming result can be displayed on web browser, I wonder that is it possible to have the website ip like “mypiip:port” instead of “backup.vos.ninja”?

**Comment by steveseguin** [comment]
You have two ways to do that.

1. Use iframes, so the video is embedded in your site as an iframe -- it will appear as  your domain then.  (https://docs.vdo.ninja/guides/iframe-api-documentation)

2. Deploy the vdo.ninja github code, host it yourself, and the video should be available on that, instead of vdo.ninja.  (so long as the wss servers are the same, this is easy)
