### ISSUE TITLE
Stream Ricoh Theta Z1 from Jetson Nano

### ISSUE THREAD

**Issue by stevenuecke7** [steveseguin/raspberry_ninja#28]
We are trying to use an equirectangular video from the Ricoh Theta Z1 plugged into our Jetson Nano using USB3 (not WIFI) as the video source to stream through this solution. We have been able to get gstreamer to show the stream using this guide: https://codetricity.github.io/theta-linux/

Do you have any suggestions as to steps we can take to get this to work? We are able to successfully stream the CSI/2 camera over vdo.ninja using your Nvidia image, but are not getting it to recognize the Ricoh Theta Z1 as a video source.

Any assistance would be greatly appreciated!

**Comment by steveseguin** [comment]
I have a Z1  so I'll give it a test and see if I can get it working

**Comment by stevenuecke7** [comment]
That would be so awesome, thank you! Vdo.ninja is the best documented single-contributor repo I've ever seen on Github - thanks so much for your ground-breaking efforts on this project!

**Comment by steveseguin** [comment]
Well, it's all working.

Pull the newest version of the repo to your Jetson and run the installer:
https://github.com/steveseguin/raspberry_ninja/blob/main/nvidia_jetson/theta_z1_install.sh

If you have problems, let me know.  The nice thing to see is you can stream direct to the web, without transcoding if you wanted to, but it will use up about 150-mbps of bandwidth.  So I recommend using it in transcode mode.

![image](https://user-images.githubusercontent.com/2575698/216748815-aca6d989-c98c-434c-a30f-6787b6fa290a.png)

**Comment by stevenuecke7** [comment]
Perfect, thanks! For a while I was getting an error about a missing thetauvc gstreamer plugin, which I tried reinstalling a few times. Eventually I ran the theta_z1_install.sh again and it worked.
Thanks so much!
