### ISSUE TITLE
Hello，Do you  have  raspberry 64bit  system？

### ISSUE THREAD

**Issue by Rethen** [steveseguin/raspberry_ninja#29]
Hello，Do you  have  raspberry 64bit  system？

**Comment by steveseguin** [comment]
I think I tried at one point, but ran into numerous issues.  64bit is not really needed I think for the images to work though, since video encoding is pretty low of memory demands.  I didn't want to waste too much time on it as a result.

Not sure if you need 64bit for other reasons, but I did provide the installation script I used last year to make the 32 bit images: https://github.com/steveseguin/raspberry_ninja/blob/main/raspberry_pi/installer.sh

If there's a good reason for needing it, I can try to find time to make a 64bit updated image.

**Comment by Rethen** [comment]
> I think I tried at one point, but ran into numerous issues. 64bit is not really needed I think for the images to work though, since video encoding is pretty low of memory demands. I didn't want to waste too much time on it as a result.
> 
> Not sure if you need 64bit for other reasons, but I did provide the installation script I used last year to make the 32 bit images: https://github.com/steveseguin/raspberry_ninja/blob/main/raspberry_pi/installer.sh
> 
> If there's a good reason for needing it, I can try to find time to make a 64bit updated image.

Because I need to install tflite-runtime and tflite-support, the two cannot be installed on the 32-bit system of the Raspberry Pi, or there are tricky problems after installation

**Comment by Rethen** [comment]
> I think I tried at one point, but ran into numerous issues. 64bit is not really needed I think for the images to work though, since video encoding is pretty low of memory demands. I didn't want to waste too much time on it as a result.
> 
> Not sure if you need 64bit for other reasons, but I did provide the installation script I used last year to make the 32 bit images: https://github.com/steveseguin/raspberry_ninja/blob/main/raspberry_pi/installer.sh
> 
> If there's a good reason for needing it, I can try to find time to make a 64bit updated image.

This website teaches you how to do RTMP streaming on GStreamer

https://qengineering.eu/install-gstreamer-1.18-on-raspberry-pi-4.html

**Comment by steveseguin** [comment]
This installation is primarily for WebRTC low-latency streaming.  If you just need RTMP, you can do something like this:
```
sudo apt-get install libx264-dev libjpeg-dev
sudo apt-get install libgstreamer1.0-dev \
     libgstreamer-plugins-base1.0-dev \
     libgstreamer-plugins-bad1.0-dev \
     gstreamer1.0-plugins-ugly \
     gstreamer1.0-tools \
     gstreamer1.0-gl \
     gstreamer1.0-gtk3
sudo apt-get install gstreamer1.0-qt5
sudo apt-get install gstreamer1.0-pulseaudio
```

Then use something like this
```
gst-launch-1.0 libcamerasrc ! video/x-h264, width=1280, height=720, framerate=30/1 ! flvmux ! rtmpsink location='rtmp://localhost/path/to/stream live=1'
 ```

**Comment by steveseguin** [comment]
I haven't tested it, but that's loosely the idea.  You can use ChatGPT probably to customize the command line, if you aren't comfortable with Gstreamer

**Comment by Rethen** [comment]
> 

ok  i  will try ，Thank you

**Comment by Rethen** [comment]
> 我还没有测试过，但这就是大致的想法。如果您对 Gstreamer 不满意，您可以使用 ChatGPT 来自定义命令行
> 
> 如果你需要构建一个 gstreamer 插件，比如一些 h264 编码器，那就更麻烦了，但我想有一些选择可以绕过它。
> 
> Raspberry.Ninja 确实有一个使用起来非常简单的 RTMP 输出选项，但目前是 32 位的。

I hope that the 64-bit image can be launched as soon as possible. Maybe many problems have been solved now, because 32-bit has been eliminated by most manufacturers.

**Comment by steveseguin** [comment]
It takes a few hours for me to build an image, assuming there are no problems.  I can try to do it while working today, but if there are issues, I can't offer promises.

**Comment by Rethen** [comment]
> 假设没有问题，我需要几个小时来构建图像。我可以在今天工作的时候尝试去做，但如果有问题，我不能承诺。

ok，thanks very much

**Comment by Rethen** [comment]
> 

erroneous pipeline: could not link libcamerasrc0 to flvmux0, libcamerasrc0 can't handle caps video/x-h264, width=(int)1280, height=(int)720, framerate=(fraction)30/1

I  don't  konw why,   chatgpt can't give me a satisfactory answer

**Comment by Rethen** [comment]
> It takes a few hours for me to build an image, assuming there are no problems. I can try to do it while working today, but if there are issues, I can't offer promises.

Hi，Bro，I  succeed build on the  Raspberry os 64 bit，it's run's  good

**Comment by steveseguin** [comment]
Awesome!  I'm currently building it myself, but I'm glad you've gotten it working.

![image](https://user-images.githubusercontent.com/2575698/228822452-bb3d4eb5-46fa-4288-9927-cb9ac0ee527e.png)

**Comment by Rethen** [comment]
> Awesome! I'm currently building it myself, but I'm glad you've gotten it working.
> 
> ![image](https://user-images.githubusercontent.com/2575698/228822452-bb3d4eb5-46fa-4288-9927-cb9ac0ee527e.png)

I  think  it's necessary for 64bit img  ，Because I spent a lot of time, including solving some difficult dependency library problems, if it is a direct mirror file, it will be much easier

**Comment by Rethen** [comment]
> Awesome! I'm currently building it myself, but I'm glad you've gotten it working.
> 
> ![image](https://user-images.githubusercontent.com/2575698/228822452-bb3d4eb5-46fa-4288-9927-cb9ac0ee527e.png)

I had to comment some of the parameters of the audio input for it to work
![image](https://user-images.githubusercontent.com/7802673/228824597-081f2408-35d8-44e8-9efe-1a894e149dc8.png)
Otherwise I will get the error

![image](https://user-images.githubusercontent.com/7802673/228824831-3154ad0e-af0f-472e-8394-51b6042419ca.png)

**Comment by Rethen** [comment]
> Awesome! I'm currently building it myself, but I'm glad you've gotten it working.
> 
> ![image](https://user-images.githubusercontent.com/2575698/228822452-bb3d4eb5-46fa-4288-9927-cb9ac0ee527e.png)

This  is  my  GStreamer's  version

![image](https://user-images.githubusercontent.com/7802673/228825495-570ab93a-dcf7-484d-bd25-919f790e5fbb.png)

**Comment by steveseguin** [comment]
That's gstreamer version is a bit old, but if you are just using RTMP and its working, then it's fine.

**Comment by Rethen** [comment]
> That's gstreamer version is a bit old, but if you are just using RTMP and its working, then it's fine.

Hello,Bro ,I  have a  new Problem, 
I want to get each frame from the pipeline for tflite object detection, but the Message type I get is None


![image](https://user-images.githubusercontent.com/7802673/229013088-4250422b-b18d-4459-9063-8bfd928e7d4e.png)

**Comment by Rethen** [comment]
> That's gstreamer version is a bit old, but if you are just using RTMP and its working, then it's fine.

I  try run publish.py，but  it's  also  print none


![image](https://user-images.githubusercontent.com/7802673/229016745-b32786e9-9db1-4ba0-b265-e2031960cb94.png)


![image](https://user-images.githubusercontent.com/7802673/229016800-ca0f600f-1039-4455-a1e7-6f2ac89ed641.png)

**Comment by steveseguin** [comment]
I'm not really sure what this has to do with Raspberry Ninja or how you are trying to approach this.

I published some GPLv3-licensed source code on how to process from Gstreamer into OpenCV/Python some years ago:

Read frames using the appsink element, then converting into raw frames for numpy/cv2/tensorflow:
https://github.com/ooblex/ooblex/blob/f974894d8ec0355009615cfab5f654f108862288/code/decoder.py#L84

This is how the appsink element is used
https://github.com/ooblex/ooblex/blob/f974894d8ec0355009615cfab5f654f108862288/code/decoder.py#L141

I can't help you develop your project, as I have my own work to do, but everything you need is there I think.

**Comment by steveseguin** [comment]
If you have a request for me to add something to Raspberry Ninja, or are willing to contribute to the code base, I'd be more able to find time to help.

**Comment by steveseguin** [comment]
I tried building 64bit, and while I was able to build it, none of the hardware accelerators are working.  The 64bit version is still too niche, and driver support is still lacking.  I'm not going to spend anymore time on it at the moment, since without the hardware acceleration, performance is pretty poor.

For those wishing to try, the installer_buster.sh file is in the rpi folder with the install script I was using.  If hardware support can be added, I may consider officially adopting 64bit going forward then.

**Comment by steveseguin** [comment]
https://drive.google.com/file/d/1vWkznU544qkRsal1GyIj4YZ-O2pNFCfh/view?usp=drive_link

I have a 64bit pre-build hosted version up now, and the installer.sh for the rpi is now configured to work with the 64bit bullseye image.

The hardware encoder seems stable now with the 64 bit version.

Closing.
