### ISSUE TITLE
Audio support on HDMI to USB 2.0 adapter?

### ISSUE THREAD

**Issue by edinsof** [steveseguin/raspberry_ninja#9]
Hi.
I fully run it on raspberry pi model 3 B v1.2
If connect a gopro with HDMI to USB 2.0 adapter will work with audio ?
![raspberryimage2](https://user-images.githubusercontent.com/3094013/131208505-9899206d-a01e-4418-b9b0-00c93441cec2.jpg)
![raspberryimage](https://user-images.githubusercontent.com/3094013/131208506-594bb968-1534-4080-b8d5-c95c7e715467.jpg)

**Comment by steveseguin** [comment]
nice!

There are some instructions on how to get audio working.  Myself and others have audio working, though you need to tweak the gstreamer pipeline a small bit depending on your device.  It shouldn't be hard to get working.

I think a GoPro has audio out over HDMI; you might want to confirm that first.

**Comment by edinsof** [comment]
raspberry_ninja don't works with self hosted version ?

**Comment by steveseguin** [comment]
It should be compatible with self-hosted website deployments of VDO.Ninja; you'll need to point the wss:// url to wss13.obs.ninja:443, instead of the backup wss one that is set by default.

If you deployed a private wss server, it might work, but I haven't tried yet with that yet. This project is still quite young and I have pretty limited free time, but I can add it to my list of things to test/add if that's what you are referring to.

**Comment by edinsof** [comment]
I have tried changing wss server to my hosted version but the image does not work

**Comment by steveseguin** [comment]
okay.  I'll update the code and will let you know when I have it working.  thank you for letting me know it isn't working for you.

**Comment by steveseguin** [comment]
https://github.com/steveseguin/raspberry_ninja/blob/self-hosted-server-patch/nvidia_jetson/server.py

Here is a version that works with the Jetson using gstreamer 1.18

if you're using gstreamer 1.14, I'll need to probably make a version for that, although my hope is to release a raspberry pi version that is 1.18 friendly sometime in the coming week or two.

**Comment by edinsof** [comment]
I tried the self-hosted patch and it works fine, but if I restart the raspberry it won't work again.

![wss request](https://user-images.githubusercontent.com/3094013/131901098-2b7ae2e4-3ff4-492e-926a-fb354129a15b.png)
![raspberrypi](https://user-images.githubusercontent.com/3094013/131901102-4a198d43-1063-4071-8549-c292a020567e.png)

**Comment by steveseguin** [comment]
I'll investigate.  thank you

**Comment by edinsof** [comment]
Solved reinstalling raspberry image on sd
